version: '3'
services:
  
  front-next:
    build: /app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app


  back-php:
    build: /PHP
    ports:
      - "8700:8700"
    volumes:  
      - ./PHP:/var/www/html